name: Jalankan Scraper Blibli

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch: 

jobs:
  scrape-data:
    runs-on: ubuntu-latest

    steps:
      - name: Ambil kode dari repository
        uses: actions/checkout@v3

      - name: Siapkan Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Jalankan script scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python scrape_blibli.py